# Generated by Django 4.2.20 on 2026-04-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
